HEADER:
  label: "Blog"

POSTS:
  - title: "Machine vision"
    category: "Technology"
    subtitle: "Machine vision (MV) its technology and methods"
    published: "2022-5-30"
    image: "config/assets/posts/blog-1.jpg"
    url: "https://shivalikcollege.edu.in/machine-vision/"

  - title: "COBOTS"
    category: "Technology"
    subtitle: "Universal Robots - advanced robotic automation"
    published: "2022-5-30"
    image: "config/assets/posts/blog-2.jpg"
    url: "https://shivalikcollege.edu.in/cobots/"

  - title: "Autonomous Cars"
    category: "Technology"
    subtitle: "The future of cars - Self-driving vehicles"
    published: "2022-5-30"
    image: "config/assets/posts/blog-3.jpg"
    url: "https://shivalikcollege.edu.in/autonomous-cars/"

  - title: "Technologies that May Impact Two Wheelers"
    category: "Technology"
    subtitle: " ABS, SLipper Clutch, TCS"
    published: "2022-5-30"
    image: "config/assets/posts/blog-4.jpg"
    url: "https://shivalikcollege.edu.in/technologies-that-may-impact-two-wheelers/"

  - title: "The V12 engine"
    category: "Technology"
    subtitle: "A twelve-cylinder piston engine"
    published: "2022-5-30"
    image: "config/assets/posts/blog-5.jpg"
    url: "https://shivalikcollege.edu.in/the-v12-engine/"

  - title: "Blockchain Oracles"
    category: "Technology"
    subtitle: "Path for the decentralized Web3 ecosystem"
    published: "2022-5-30"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/blockchain-oracles/"

  - title: "Augmented Reality"
    category: "Technology"
    subtitle: "A a geospatial datum for the virtual object"
    published: "2022-5-30"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/augmented-reality/"

  - title: "Virtual Reality"
    category: "Technology"
    subtitle: "A user’s senses sight and hearing"
    published: "2022-5-30"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/virtual-reality/"

  - title: "Cutting Edge Technology Courses After 12th Grade"
    category: "Technology"
    subtitle: "The most perplexing periods of your career"
    published: "2022-5-30"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/cutting-edge-technology-courses-after-12th-grade/"

  - title: "Mechatronics, Robotics Drone Technology is the Future of Mechanical Engineering?"
    category: "Technology"
    subtitle: "the unprecedented global economic crisis cannot dampen demand"
    published: "2022-5-30"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/mechatronics-robotics-drone-technology-is-the-future-of-mechanical-engineering/"

  - title: "Cyber Security 2.0"
    category: "Technology"
    subtitle: "Rapidly changing challenges in Security"
    published: "2022-5-30"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/cyber-security-2-0/"

  - title: "Quantum Computing"
    category: "Technology"
    subtitle: "~Not a handheld device or a cooled server "
    published: "2022-5-30"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/quantum-computing/"

  - title: "Computer Science Continues to be the No. 1 Choice in Engineering Due to Multiple Career Openings"
    category: "Technology"
    subtitle: "Prospective employment opportunities"
    published: "2022-5-30"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/computer-science-continues-to-be-the-no-1-choice-in-engineering-due-to-multiple-career-openings/"

  - title: "Infra Demands in India for the Next 3-5 Decades Makes Civil Engineering a Great Career Option"
    category: "Technology"
    subtitle: "Oldest and most advanced engineering disciplines."
    published: "2022-5-30"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/infra-demands-in-india-for-the-next-3-5-decades-makes-civil-engineering-a-great-career-option/"

  - title: "Private Universities- The Future Drivers of Higher Education"
    category: "Technology"
    subtitle: "One of the most crucial decisions"
    published: "2022-5-30"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/private-universities-the-future-drivers-of-higher-education/"

  - title: "Is Pursuing a Degree in Agriculture Worth It?"
    category: "Technology"
    subtitle: "A degree from an agriculture"
    published: "2022-5-30"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/is-pursuing-a-degree-in-agriculture-worth-it/"

  - title: "The Best Career Roles for a Computer Science Engineer"
    category: "Technology"
    subtitle: "Highest-paying careers"
    published: "2022-5-30"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/the-best-career-roles-for-a-computer-science-engineer/"

  - title: "The Various Specialisations within BBA"
    category: "Technology"
    subtitle: "Path for the decentralized Web3 ecosystem"
    published: "2022-5-30"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/blockchain-oracles/"

  - title: "Blockchain Oracles"
    category: "Technology"
    subtitle: "Pursue regardless of your experience"
    published: "2022-5-30"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/the-various-specialisations-within-bba/"

  - title: "Top Job Opportunities after a Degree in Pharmacy"
    category: "Technology"
    subtitle: "Advanced dramatically in recent years."
    published: "2022-5-30"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/top-job-opportunities-after-a-degree-in-pharmacy/"

  - title: "Why You Should Opt for Polytechnic Courses"
    category: "Technology"
    subtitle: "Contrast to the customary norm"
    published: "2022-5-20"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/why-you-should-opt-for-polytechnic-courses/"

  - title: "AI and ML Algorithms for a better future"
    category: "Technology"
    subtitle: "Ethical artificial intelligence"
    published: "2022-5-30"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/ai-and-ml-algorithms-for-a-better-future/"

  - title: "IoT Based Smart Agriculture System"
    category: "Technology"
    subtitle: "Emerging concept because IoT sensors"
    published: "2022-5-30"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/iot-based-smart-agriculture-system/"

  - title: "Pharmaceutical companies in Artificial Intelligence"
    category: "Technology"
    subtitle: "AI to streamline the process "
    published: "2022-5-30"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/pharmaceutical-companies-in-artificial-intelligence/"

  - title: "Antenna as a Specialisation"
    category: "Technology"
    subtitle: "Signal propagating and receiving"
    published: "2022-5-29"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/antenna-as-a-specialisation/"

  - title: "Infrared Guided Missile Detection System"
    category: "Technology"
    subtitle: "Sought after by various countries due to their high resolution"
    published: "2022-4-7"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/infrared-guided-missile-detection-system/"

  - title: "D.Pharm VS B.Pharm? -Which is the better Pharmacy Career Option?"
    category: "Technology"
    subtitle: "Advanced dramatically in recent years."
    published: "2022-5-30"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/d-pharm-vs-b-pharm-which-is-the-better-pharmacy-career-option/"

  - title: "IoT at Shivalik College Of Engineering."
    category: "Technology"
    subtitle: "Advanced dramatically in recent years."
    published: "2022-4-7"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/vanet-and-its-cloud-based-approaches/"

  - title: "VANET and Its Cloud-Based Approaches"
    category: "Technology"
    subtitle: "face several technical challenges in deployment"
    published: "2022-5-30"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/vanet-and-its-cloud-based-approaches/"

  - title: "SPORTS LIFE AT SHIVALIK"
    category: "Technology"
    subtitle: "Power dynamic in college sports was clear."
    published: "2022-4-4"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/sports-life-at-shivalik/"

  - title: "Scope of BSc Agriculture in India? What can I do after the B.Sc Agriculture course?"
    category: "Technology"
    subtitle: "Primary source of livelihood for the majority of Indians"
    published: "2022-3-23"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/scope-of-bsc-agriculture-in-india-what-can-i-do-after-the-b-sc-agriculture-course/"

  - title: "Why should you choose BBA after the 12th?"
    category: "Technology"
    subtitle: "Picking one of them is not so easy"
    published: "2022-3-23"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/why-should-you-choose-bba-after-the-12th/"

  - title: "Reasons to Study BSc Agriculture"
    category: "Technology"
    subtitle: "Humankind has been practicing agriculture in various forms"
    published: "2022-02-08"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/reasons-to-study-bsc-agriculture/"

  - title: "Job Profiles for Computer Science Engineers"
    category: "Technology"
    subtitle: "Tremendous opportunity to work in several career enriching job profiles"
    published: "2022-03-21"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/job-profiles-for-computer-science-engineers/"

  - title: "CSE & IT AFTER"
    category: "Technology"
    subtitle: "Hit a stumbling block: you don’t know what to choose?"
    published: "2022-03-21"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/cse-it-after-2022/"

  - title: "5 Reasons Why BBA Provides the Best Start for Your Management Career"
    category: "Technology"
    subtitle: "business of their own or continue"
    published: "2022-02-05"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/5-reasons-why-bba-provides-the-best-start-for-your-management-career/"

  - title: "Does Mechanical Engineering in India have scope in near future?"
    category: "Technology"
    subtitle: "Oldest department of engineering"
    published: "2022-02-08"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/does-mechanical-engineering-in-india-have-scope-in-near-future/"

  - title: "10 reasons Why B.Tech in civil engineering is important"
    category: "Technology"
    subtitle: "Oldest department of engineering"
    published: "2022-02-08"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/10-reasons-why-b-tech-in-civil-engineering-is-important/"

  - title: "5 Reasons to choose Pharmacy as a Career"
    category: "Technology"
    subtitle: "rapidly growing one of the most promising careers"
    published: "2022-2-1"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/5-reasons-to-choose-pharmacy-as-a-career/"


  - title: "The Past, Present and Future of Electrical Engineering Education in India"
    category: "Technology"
    subtitle: "Oldest department of engineering"
    published: "2022-01-22"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/the-past-present-and-future-of-electrical-engineering-education-in-india/"


  - title: "Career Options after Diploma in Computer Science"
    category: "Technology"
    subtitle: "Oldest department of engineering"
    published: "2022-01-22"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/career-options-after-diploma-in-computer-science/"

  - title: "Installing Mosquitto MQTT Broker on Linux (Ubuntu)"
    category: "Technology"
    subtitle: "IoT becoming a leading name"
    published: "2022-02-06"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/installing-mosquitto-mqtt-broker-on-linux-ubuntu/"

  - title: "Careers to pursue after B.Tech Electronics and Communication Engineering"
    category: "Technology"
    subtitle: "Oldest department of engineering"
    published: "2021-12-27"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/careers-to-pursue-after-b-tech-electronics-and-communication-engineering/"

  - title: "YOUR CAREER MATTERS TO US"
    category: "Technology"
    subtitle: "Technologies in education has been widely advocated"
    published: "2021-08-20"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/your-career-matters-to-us/"

  - title: "The Demand For Engineers With Managerial Skills"
    category: "Technology"
    subtitle: "Aggressive hiring of ‘T-shaped’ engineering professionals"
    published: "2021-08-24"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/the-demand-for-engineers-with-managerial-skills/"

  - title: "CYBER  SECURITY"
    category: "Technology"
    subtitle: "significant rise in its market"
    published: "2021-9-7"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/cyber-security/"

  - title: "Careers to pursue after B.Tech Electronics and Communication Engineering"
    category: "Technology"
    subtitle: "Oldest department of engineering"
    published: "2021-12-27"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/shivalik-a-game-changer/"

  - title: "Shivalik : A Game Changer"
    category: "Technology"
    subtitle: "quality education and industry-ready skills"
    published: "2021-12-27"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/shivalik-a-game-changer/"

  - title: "THE SHIVALIK COLLEGE DEHRADUN"
    category: "Technology"
    subtitle: "push boundaries to achieve research excellence"
    published: "2021-9-7"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/the-shivalik-college-dehradun/"

  - title: "HOSTEL LIFE 2.0"
    category: "Technology"
    subtitle: "where economical, healthy, and safe accommodation is provided"
    published: "2021-12-27"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/advantages-and-disadvantages-of-hostel-life/"

  - title: "The Aim of the Management"
    category: "Technology"
    subtitle: "where economical, healthy, and safe accommodation is provided"
    published: "2021-9-7"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/the-aim-of-the-management/"

  - title: "Hostel Life"
    category: "Technology"
    subtitle: "Memories which they will carry with them for life,"
    published: "2021-6-15"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/hostel-life/"

  - title: "Unique food habits Of Uttarakhand"
    category: "Technology"
    subtitle: "prime concerns for every parent"
    published: "2021-6-21"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/unique-food-habits-of-uttarakhand/"

  - title: "Shaping The Future At Shivalik"
    category: "Technology"
    subtitle: "changing at an enormous rate"
    published: "2021-6-21"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/shaping-the-future-at-shivalik/"

  - title: "HOSTEL LIFE 2.0"
    category: "Technology"
    subtitle: "where economical, healthy, and safe accommodation is provided"
    published: "2021-12-27"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/advantages-and-disadvantages-of-hostel-life/"

  - title: "INCUBATION CENTER AT SHIVALIK COLLEGE DEHRADUN"
    category: "Technology"
    subtitle: "where economical, healthy, and safe accommodation is provided"
    published: "2021-6-21"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/incubation-center-at-shivalik-college-dehradun/"

  - title: "World Environment Day"
    category: "Technology"
    subtitle: "help humans in covering for the damage that we have already done"
    published: "2021-12-27"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/world-environment-day/"

  - title: "How engineers can be active contributors to business decisions"
    category: "Technology"
    subtitle: "Must possess pragmatic decision-making abilities,"
    published: "2021-12-27"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/how-engineers-can-be-active-contributors-to-business-decisions/"

  - title: "The constant changing technology is leading to an ever"
    category: "Technology"
    subtitle: " constant changing technology is leading to an ever changing market"
    published: "2021-11-30"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/the-constant-changing-technology-is-leading-to-an-ever/"

  - title: "Top 5 projections in Artificial Intelligence"
    category: "Technology"
    subtitle: "Data biases creating problems in AI applications"
    published: "2021-5-8"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/top-5-projections-in-artificial-intelligence-for-2021/"

  - title: "How different programs helps students in understanding the industry better"
    category: "Technology"
    subtitle: "changing trend and needs of the modern industries"
    published: "2021-11-13"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://shivalikcollege.edu.in/how-different-programs-helps-students-in-understanding-the-industry-better/"